### ISSUE TITLE
Add expression for extracting header from JSON request

### ISSUE THREAD

**Issue by leandrocharlier** [castlemock/castlemock#124]

**Comment by karldahlgren** [comment]
Hi @leandrocharlier.
I have a question. I was looking closer at your pull request and I had a question. Do you have JSON in your headers? If not, would it be possible to change the RestParameterHeaderExpression to look more like RestParameterQuery.

However, if you do have JSON in your headers and need to parse the JSON information in the headers, then that makes sense. However, in that case I would like to change RestResponseStrategy enum value from HEADER_MATCH to HEADER_JSON_PATH. The reason for this is because we might want to add functionality to simply match headers.

What do you think? Any suggestions?
Thanks!
Best regards,
Karl Dahlgren

**Comment by leandrocharlier** [comment]
Hi @karldahlgren.
No, I don't have JSON in my headers, you're right, it should look more like RestParameterQuery,
Do I make that change and do another pull request?
Regards!
Leandro Charlier

**Comment by karldahlgren** [comment]
Hi @leandrocharlier.
Cool! No need, I can do it tomorrow. Should be very minor changes. I was thinking about porting the functionality to SOAP project as well 😄 
I just wanted your confirmation 😄 

Once again, thank you so much.
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Is that fine with you @leandrocharlier?
If you really wanna do it then I won't stop you 😄 

Best regards,
Karl Dahlgren

**Comment by leandrocharlier** [comment]
Hi @karldahlgren. 
It's okay for me, thanks for doing it, anything you need, let me know :)

Regards!
Leandro Charlier
