### ISSUE TITLE
Update web configuration for Castlemock app

### ISSUE THREAD

**Issue by DarwinOnLine** [castlemock/castlemock#126]
When I have an heavy project with large mocked responses, if I want to import them later, I have this error :

> Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$FileSizeLimitExceededException: The field files exceeds its maximum permitted size of 1048576 bytes. 

So a upload size limit set to 1M, that is a little weak.

I would like to add some tomcat configuration to set that from docker-compose or Dockerfile, how to do that ?

**Comment by karldahlgren** [comment]
I agree @DarwinOnLine.
I considering to change the default limit. What is the size of your project?

Thanks!
Best regards,
Karl Dahlgren

**Comment by DarwinOnLine** [comment]
About 10M+, we cannot set this limit ourselves ?

Best regards

**Comment by karldahlgren** [comment]
Hi @DarwinOnLine.
The default value can be configured by providing the following properties:

	spring.servlet.multipart.max-file-size=10MB
	spring.servlet.multipart.max-request-size=10MB

I have updated the default value for future Castle Mock releases to be 20MB. I have also made it possible to easily override the max file size by providing the following property instead of overriding two properties: server.upload.max-size

Example:

	server.upload.max-size=50MB

The new release of Castle Mock will be released at the end of the week (Meaning tomorrow).

Once again, thank you for raising this issue.
Best regards,
Karl Dahlgren

**Comment by eghitescu** [comment]
> Hi @DarwinOnLine. The default value can be configured by providing the following properties:
> 
> ```
> spring.servlet.multipart.max-file-size=10MB
> spring.servlet.multipart.max-request-size=10MB
> ```
> 
> I have updated the default value for future Castle Mock releases to be 20MB. I have also made it possible to easily override the max file size by providing the following property instead of overriding two properties: server.upload.max-size
> 
> Example:
> 
> ```
> server.upload.max-size=50MB
> ```
> 
> The new release of Castle Mock will be released at the end of the week (Meaning tomorrow).
> 
> Once again, thank you for raising this issue. Best regards, Karl Dahlgren

Hi, can you tell me in which file do i have to write

 ```
> server.upload.max-size=50MB
> ```
?
