### ISSUE TITLE
"Forwarded" working, but "Recording" or "Record once" is not

### ISSUE THREAD

**Issue by fcrbe** [castlemock/castlemock#157]
When I put a port on "Forwarded", it is working properly. However, when switching the status to "Recording" or "Record once", I get a response body with:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error-response/>

Nothing else changes though (using postman to send the request, request body & headers remain the same).

Any specific place where I could start digging in?

**Comment by karldahlgren** [comment]
Hi @fcrbe.
Thank you so much for finding and reporting this issue. The problem occurred when trying to create new mocked responses when using the recording mode. This issue seems to have been introduced quite recently. Nice catch!

The fix will be part of next release and I will prepare a new release before the end of this week.
Once again, thank you so much for reporting this.

Best regards,
Karl Dahlgren
