### ISSUE TITLE
[Docker] 'Address' show docker-IP instead of Container-IP

### ISSUE THREAD

**Issue by doanva84** [castlemock/castlemock#225]
**Describe the bug**
'Address' of a method should use Container-IP

**To Reproduce**
1. Deploy Castle-mock using Docker (Assumption: docker-IP = a.b.c.d, container-IP = k.l.m.n)
2. Create a sample Project/App/Resource then method
3. See error: 'Address' showed http://a.b.c.d:PORT/castlemock/mock/rest/project/<project-code>/application/<app-code>/<resource-uri>

**Expected behavior**
'Address' showed http://k.l.m.n:PORT/castlemock/mock/rest/project/<project-code>/application/<app-code>/<resource-uri>

**Additional context**
I need to copy 'Address' value and replace container-IP at place of docker-IP to postman or console while trying to test a resource/method.

**Comment by Khan-Tzar** [comment]
I have also problem with the URL. 

I started Castle Mock as Docker container and it has internal IP which is not seen outside but we 
assigned an external IP address as alias host's machine network card and dedicated to this container in order to be accessed outside.  

Into the Castle Mock I see generated URL with IP 172.17.0.3:80 which is the IP granted by Docker engine to the container but I access the application via an IP from our network for example http://10.8.7.55 .  

How can make instead  
http://172.17.0.3:80/castlemock/mock/rest/project/VCahIg/application/d8PIdl/svc/cases/{caseRef}/elements/sales-recovery/{docRef}

To have 
http://192.168.0.5/castlemock/mock/rest/project/VCahIg/application/d8PIdl/svc/cases/{caseRef}/elements/sales-recovery/{docRef}
 

![mock-service](https://user-images.githubusercontent.com/29702138/83254590-b79f9f00-a1b7-11ea-85e8-315119b1017a.png)

**Comment by doanva84** [comment]
@karldahlgren: I think the root cause is : invokeAddress is building from internal request.
In fact, it should be built from external container (In JavaScript, external address may be get via 
`var invokeAddress_ROOT = window.location.origin //Reference: https://stackoverflow.com/questions/6941533/get-protocol-domain-and-port-from-url`

1. https://github.com/castlemock/castlemock/blob/master/web/mock/rest/src/main/resources/META-INF/resources/WEB-INF/views/partial/mock/rest/resource/restResource.jsp#L50
2. https://github.com/castlemock/castlemock/blob/master/web/mock/rest/src/main/java/com/castlemock/web/mock/rest/web/view/controller/resource/RestResourceController.java#L85

And

1. https://github.com/castlemock/castlemock/blob/master/web/mock/rest/src/main/resources/META-INF/resources/WEB-INF/views/partial/mock/rest/method/restMethod.jsp#L55
2. https://github.com/castlemock/castlemock/blob/master/web/mock/rest/src/main/java/com/castlemock/web/mock/rest/web/view/controller/method/RestMethodController.java#L101

**Comment by trulex** [comment]
Are there any workarounds for this issue?

**Comment by karldahlgren** [comment]
Hi @trulex.
I'm hoping to get some time over soon to look into this issue. I believe that the approach that @doanva84 suggesting might be the best long-term solution. In the meantime, what you could do is set the following environment setting to your IP-address or hostname: server.endpoint.address. Your configured value will be shown instead of the IP-address.

Example:

     server.endpoint.address = castlemock.herokuapp.com
