### ISSUE TITLE
WSDL file import - no ports generated

### ISSUE THREAD

**Issue by pauledavey** [castlemock/castlemock#287]
I have imported and executed the docker image
docker pull castlemock/castlemock
docker run -d -p 8080:8080 castlemock/castlemock
Created new project called Test, select type as SOAP
Import WSDL files from local source (zip attached to this post) - selected all files and subfolder
Import states successful, but there are no ports created

**Expected behavior**
See ports and be able to make calls
**Desktop (please complete the following information):**
Windows 10, docker image
[vim25.zip](https://github.com/castlemock/castlemock/files/5378283/vim25.zip)

**Comment by karldahlgren** [comment]
Hi @pauledavey.
My apologies for the late response here.
The problem here is that your WSDL file is divided into separate WSDL files, which currently is not supported in Castle Mock. Castle Mock expects the WSDL-file that is uploaded to be complete and not reference other WSDL files.

At the moment, it is not supported, but it might be in the future.
Thank you for reporting this issue.
Best regards,
Karl Dahlgren
