### ISSUE TITLE
how can I import WSDL with xsd imports?

### ISSUE THREAD

**Issue by diegocastillomck** [castlemock/castlemock#46]
Hi,

Thank you for such a great tool. I'm just facing an issue related to a special WSDL with <xsd:import> and <xsd:include> that aren't imported and the mocks servers don't work.

Is there a way to import the imports and includes somehow?

Thanks,

**Comment by karldahlgren** [comment]
HI @diegocastillomck.
Thank you very much for the kind words and for using Castle Mock!
Castle Mock ignores imports and includes since they are often quite problematic to deal with (Relative paths, problems with accessibility and so on). Nevertheless, I would very much like to investigate this particular problem. Would it be possible for you to provide an example WSDL on how your setup looks like?

Best regards,
Karl Dahlgren

**Comment by mhewedy** [comment]
@diegocastillomck I've worked with some WSDLs that have the same issue, but they provided a single wsdl as well, this is what I mean: https://stackoverflow.com/questions/25277536/what-is-the-difference-between-wsdl-and-singlewsdl-parameters

**Comment by karldahlgren** [comment]
Hi @diegocastillomck.
Did you manage to resolve your issue? Can I close this?

Thank you.
Best regards,
Karl Dahlgren

**Comment by karldahlgren** [comment]
Closing this issue. Please feel free to contact me again if you need help in the future.
