### ISSUE TITLE
Responses for encoded query param

### ISSUE THREAD

**Issue by wedla** [castlemock/castlemock#471]
Hello, Karl, I'm facing this issue: my team developed a feature that consists of an integration between a REST API to another REST API, however, this last one has a GET endpoint that receives a XML as query param. 

Debugging our application, we find out that the Python library sends the request with the query param encoded, so I put the query value on Castlemock also encoded, but I'm always getting Internal Server Error, like it has no response, when, indeed, it was set to have.

![image](https://user-images.githubusercontent.com/15742763/154788374-b5247977-55ce-4ba5-b0eb-b032d213b0c7.png)
![image](https://user-images.githubusercontent.com/15742763/154788105-e5bf66a7-b8cf-4417-817c-ac93b7ddec48.png)

Also, if I decode the URL, I get a valid XML, as you can see below:

![image](https://user-images.githubusercontent.com/15742763/154788258-c3326a14-590f-4d97-8c85-e3445ad1d31e.png)

I created a github repo to be used as volume (in case you want to use Docker) with the application I created on Castlemock. Here's the link: https://github.com/wedla/encodedQueryParam

Hope you can help me with this! I appreciatte since now all the help you can give me, and I wish a great weekend ;-)

**Comment by karldahlgren** [comment]
Hi @wedla!
Great to hear from you again and thank you for raising this issue.
I looked into the issue and it seems that the query parameters gets decoded by default, which makes it a little bit problematic when doing pattern matching. The use case by sending XML might be uncommon. However, the scenario where you want to handle the parameters as encoded value seems like a valid use case.

I have added support so that you can specify that you want the parameter to be handled as an encoded value when creating query parameters. This should allow you to match with encoded parameters.

I will include this in the next release and hopefully be able to release a new version by the end of the day.

Cheers!

![Screenshot from 2022-02-20 13-10-15](https://user-images.githubusercontent.com/4678380/154841811-7b6188ed-dc7d-45d9-a27e-6b6f69d60574.png)

**Comment by wedla** [comment]
Dear @karldahlgren, I don't have enough words to thank you for all your support. Thank you very much for this, you're an amazing human being. 

I wish all the best for you and your family.

I'm gonna close the issue since it is completed :) I tested it and it is ok.

Have a great week! Cheers!
