### ISSUE TITLE
MongoDb Support

### ISSUE THREAD

**Issue by fatihhkuru** [castlemock/castlemock#501]
Why did you remove MongoDb support? How can i use mongodb?

**Comment by karldahlgren** [comment]
I decided to remove the MongoDB support for multiple reasons. Firstly, the MongoDB was an experiment on how an alternative storage solution might look like. Secondly, the MongoDB implementation frequently caused issues during upgrades and made it harder to maintain and upgrade Castle Mock. Since the MongoDB storage solution was never documented or announced I decided to remove it for now.

I might add support for MongoDB or any other storage solution in the future. However, for now there won't be any MongoDB support.
