### ISSUE TITLE
Imported Soap project returns only errors when Sequence Strategy is selected

### ISSUE THREAD

**Issue by DFranzen** [castlemock/castlemock#57]
I imported my xml file as new soap project and it works fine as long as I select "Random" as Response strategy. However as soon as I change the strategy to Sequence I get only 

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error-response/>

as mock response. Am I doing something wrong?

**Comment by karldahlgren** [comment]
Hi @DFranzen.
Thank you for raising this bug. The problem was that the current sequence number wasn't exported which resulted in sequence number being null when importing the SOAP project. The problem occurred in version 1.21. The issue has now been resolved. I have created a new release (1.22). It can either be downloaded from the webpage (https://castlemock.com/) or from Docker.

I apologies for the inconvenience and thank you again for bringing this to my attention.
Please feel free to create more tickets if you find anything else or need any support.

Best regards,
Karl Dahlgren

**Comment by DFranzen** [comment]
Thanks for the quick update. I downloaded the new docker image, but I still have some issues with the Sequence Strategy:
- If I import my xml-file now and CHANGE the strategy to Sequence I still get the same error message. Only once I export the changed project and reimport it, it starts working. Is there still a problem with changing to Sequence maybe?
- The order of the responses after the (original) import is not as in the xml-file. That means my sequence is screwed up. My file has the mock responses embedded in each operations-block (I noticed the export now puts the responses outside and references the operationid). The ids for the responses are in ascending order, I have no idea where the new order comes from.
