### ISSUE TITLE
Castle mock application crash.

### ISSUE THREAD

**Issue by jeevitesh** [castlemock/castlemock#592]
Hi,
We have noticed the castle mock server gets crashed frequently in the span of 3 months twice the castle mock instance has crashed which resulted in loss of the projects . So is there any way we can take to automatic backup ! or is there any better solution.

**Comment by karldahlgren** [comment]
Hi @jeevitesh 
I'm assuming that you are using the Docker image. If so, please read the documentation on how to persist Castle Mock project files outside the docket image: https://github.com/castlemock/castlemock/wiki/Docker#persistence

By doing this, you will keep all files if you have to restart the Docker image. 

Please read the documentation before creating new issues and if you have to create a new issue, please use the GitHub issue template.

**Comment by jeevitesh** [comment]
Hi @karldahlgren 
We are using kubernetes with persistent disk. I suspect a bug in castle mock made the application to crash and all the project which were created are lost. So i requesting your help how to take the automatic backup (apart from manual process).
with regards
jeevitesh

**Comment by karldahlgren** [comment]
Hi @jeevitesh 
All the files related to Castle Mock, such as projects, are stored on the file system in a folder named .castlemock in the home directory. You could just copy that folder in order to make a backup. Keep in mind that Castle Mock on reads from these files on startup. So you need to restart the application for these files to be loaded into the Castle Mock.

Alternatively, you could use the REST api to export and import projects.

Both of these approaches could be achieved by configuring a cron job.

Regarding the crashes: I haven't heard of the application crashing before. Could be something with your setup or too little memory is given to Castle Mock. Hard to tell.

Good luck!
