### ISSUE TITLE
DB Storage plans

### ISSUE THREAD

**Issue by milkotodorov** [castlemock/castlemock#90]
Is there are any plans considering storage into a DB instead of FS?

**Comment by karldahlgren** [comment]
Yes and no. 😄 
Castle Mock is built in such a way that it should be easy to add database support in the future. In theory it should be quite easy to add support for it. However, there is no plans right now to start adding this support.
My approach has been that I would wait until someone requests it. I guess that day just came 😄 

What do you think? Should we add support for DB? If so, what kind of DB?

Best regards,
Karl Dahlgren

**Comment by mhewedy** [comment]
I like the current file-based storage solution. 

And If DB support is needed, we need to make it optional and to support multiple DBMS (mysql, postgres, sqlite, etc ...)

**Comment by karldahlgren** [comment]
Absolutely. I agree with you 100%. Castle Mock will always have file-based storage. One of the strengths with Castle Mock is that it is easy to setup. Simply deploy it to a Tomcat and then you are up and running.

My idea was to have different profiles for each implementation (FS, MySQL, MongoDB and so on). The repository layer is separated so that it would be easy in the future to add multiple implementations of the repository. We could add the [@]Profile annotation on the repository implementation and use different once depending whether you want FS or DB. However, the default will always be file-based storage.

What do you think about that, @mhewedy? 😃 

As always, great input.
Best regards,
Karl Dahlgren

**Comment by milkotodorov** [comment]
I do agree with @mhewedy having multiple DBs support especially when the effort for it won't be very big. We'll do benefit of it as we are facing issues with the future of the permanent FS in our internal cloud. FS of course I find it too nice to be the default. I would suggest string with Postgres.

**Comment by mhewedy** [comment]
@karldahlgren Looks very good idea to me.

I am thinking of creating some post-installation pages that allow the user to do select from multiple data sources and do the configuration for it. (same as Jenkins, bamboo, etc) (require more work)

Or 
To allow the user to go dirty and do the configuration himself.

Which way to follow?

**Comment by karldahlgren** [comment]
@mhewedy I think we could start by simply allowing the users to configure it in a configuration file and see how big the demand is. I agree that in the long run it would be nice to have a post-installation page which allows the users to configure it more simplistic and elegant, but there are other things I would rather prioritize first 😄 

Best regards,
Karl Dahlgren

**Comment by mhewedy** [comment]
I We need to implement 5 Repositorys:

com.castlemock.web.mock.soap.model.project.repository.SoapProjectRepository
com.castlemock.web.mock.rest.model.project.repository.RestProjectRepository
com.castlemock.web.mock.rest.model.event.repository.RestEventRepository
com.castlemock.core.basis.model.user.repository.UserRepository
com.castlemock.web.mock.soap.model.event.repository.SoapEventRepository

![screen shot 2018-11-16 at 10 45 40 am](https://user-images.githubusercontent.com/1086049/48605097-de5b0380-e98c-11e8-8911-da80e74740b0.png)

@karldahlgren How do you suggest to start? should we depend on JPA (might require changes on the domain model?) or Jdbc ? I think adapting Jdbc will give us 2 points, simplicity (no need to change current domain model - if any) and flixability.

What do you think?

**Comment by mhewedy** [comment]
@karldahlgren Yes, I do. Let me give it a try and will come back to you with the results.

**Comment by mhewedy** [comment]
Hi @karldahlgren,

I've done some basic implementation for `MongoRepository` which I think is the basic class here and which will require writting extensive unit testing.

Please review [this patch file](https://github.com/castlemock/castlemock/files/2606175/90._DB_Storage_plans_.mongodb.patch.zip) and let me know your feedback.

The next step is to writting extensive unit tests for `MongoRepository`, and then implement the class `UserMongoRepository` which will be a very straightforward task.

Note: 
1. I've chosen the name `Mongo` instead of `Mongodb` hence everywhere in mongodb driver and spring, `Mongo` is being used over `Mongodb`
2. I've based my implementation on `o.s.d.m.r.s.SimpleMongoRepository` as possible.
3. I've decided not to implement `exportOne` and `importOne` as I think it is not unsed in the code but in the `LegacyRepository`.

**Comment by mhewedy** [comment]
I think it is better to have different issues for different types of db support.

And leave this one for mongodb.

**Comment by karldahlgren** [comment]
I agree @mhewedy.
We will close this one and open a new ticket if we need to implement another repository.

**Comment by milkotodorov** [comment]
Thanks for the MongoDB support. Is there any doc how to enable it?

**Comment by karldahlgren** [comment]
Hi @milkotodorov.
Sorry for the late response. I haven't configured the MongoDB for a while, but last I looked it was configured the following way:

```
java -jar code/deploy/tomcat/jar/build/libs/castlemock.jar \
	 --spring.profiles.active=mongodb \
	 --spring.data.mongodb.port=27018 \ 
	 --spring.data.mongodb.database=mycastlemockdb
```

I will try to set this up as soon as I get some spare time.
Best regards,
Karl Dahlgren
